### ISSUE TITLE
Struggling with x-class binding

### ISSUE THREAD

**Issue by jackmcdade** [calebporzio/project-x#1]
First of all, I love this. This declarative approach is why I fell in love with Vue.js in the first place, and the bigger and more robust Vue gets, the less I want to use it on small projects.

Okay so I'm trying to make buttons that hide themselves when you click them, and I must be doing something simple and dumb, but I can't get it to work. Here's my fiddle: <https://jsfiddle.net/c6at2e7z/>

Any ideas?

**Comment by dardanmulaj** [comment]
Just like with the "Here I am" element, you have to do `x-bind:class` rather than `x-class`.

**Comment by jackmcdade** [comment]
I knew I did something noobish and dumb 😆 thanks! Could have sworn I was just copying and pasting from the docs, but clearly not.
