### ISSUE TITLE
[Question] How to toggle the 'disabled' atrribute with Project-X?

### ISSUE THREAD

**Issue by guillermo7227** [calebporzio/project-x#12]
If we have a `<button>click me</button>`, I want to add the `disabled` attribute using a condition. I want something like `<button x-toggle:disabled="myVar">click me</button>`. When `myVar` is falsy, the attribute will not be rendered and viceversa. Instead of `myVar` it can also be any javascript that return falsy or truthy values.

I'm currently getting this behaviour by using `x-bind:class` but I was wondering if one could toggle attributes.

**Comment by calebporzio** [comment]
`<button x-bind:disabled="myVar"></button>`

Project-X supports attribute binding, AND supports boolean attribute binding.

This should be exactly what you're looking for.

**Comment by guillermo7227** [comment]
Thanks. I added a pull request with a lil bit of documentation for this. Probably this is a doubt other people will have too. [here](https://github.com/calebporzio/project-x/pull/13).
