### ISSUE TITLE
`x-bind:class` doesn't watch nested keys

### ISSUE THREAD

**Issue by thormeier** [calebporzio/project-x#14]
Hello,

first of all, thank you for this amazing piece of software!

I started playing around with and noticed that at least `x-bind:class` doesn't watch nested keys. Code to reproduce:

```html
<div x-data="{ foo: { bar: false }, baz: false }">
    <!-- Doesn't work, the class doesn't get attached on click. -->
    <p x-bind:class="{ 'works': foo.bar }" x-on:click="foo.bar = true">
        Lorem ipsum dolor sit amet
    </p>

    <!-- Shows true when upper paragraph has been clicked. -->
    <button x-on:click="console.log(foo.bar)">Check foo.bar</button>

    <!-- Works, the class gets attached properly as soon as clicked. -->
    <p x-bind:class="{ 'works': baz }" x-on:click="baz = true">
        Lorem ipsum dolor sit amet
    </p>
</div>
```

The button shows that the nested key is indeed being changed, but `x-bind` doesn't seem to recognize this change. 

As a workaround, one could just avoid nested keys or use functions to achieve this, but that doesn't seem very practical.

Any ideas?

Regards

**Comment by keyurshah** [comment]
We're seem to be having a a similar issue with x-model and data objects. 

https://codepen.io/kjshah/pen/3da938c8e6039bf2d8778eca20668c58?editors=1010

**Comment by thormeier** [comment]
@calebporzio @keyurshah I investigated the code a bit. Seems like the it uses Proxies in the back to keep track of changes, but only ever wraps the first level. I'm working on a PR for this.

**Comment by thormeier** [comment]
Can be closed, as the PR got merged. Thanks again :)
