### ISSUE TITLE
Unhandled Promise and Unexpected Token

### ISSUE THREAD

**Issue by shaqaruden** [calebporzio/project-x#15]
![Screen Shot 2019-12-09 at 2 59 31 PM](https://user-images.githubusercontent.com/5414897/70468177-9d042d00-1a94-11ea-827a-0abcdcd12cf6.png)

**Comment by shaqaruden** [comment]
Here's some more context 

![Screen Shot 2019-12-09 at 3 02 19 PM](https://user-images.githubusercontent.com/5414897/70468360-f3716b80-1a94-11ea-9a5b-0257269f29f2.png)

**Comment by calebporzio** [comment]
Long shot, do you have any empty `x-data` attributes? Or empty `x-` attributes at all? This would cause this. Maybe paste in the offending code.

**Comment by shaqaruden** [comment]
I missed a empty x-tex.
