### ISSUE TITLE
Working with a Date Object is difficult

### ISSUE THREAD

**Issue by shaqaruden** [calebporzio/project-x#22]
I am working on a Project-X Date Picker. I can define a date object by defining a method that returns the date object

```javascript
today() { return new Date() }
```

where I run into issue is when I want to create mutable properties for the day, month and year. I tried this two ways. First I trying defining date method that returns a object that has 3 child objects (day, month and year) with each one of those containing a a selected and current property. This does work but I cannot mutate the properties.

```javascript
 date() { 
                    return {
                        day: {
                            current: this.today().getDate(),
                            selected: this.today().getDate()
                        },
                        month: {
                            current: this.today().getMonth(),
                            selected: this.today().getMonth()
                        },
                        year: {
                            current: this.today().getFullYear(),
                            selected: this.today().getFullYear()
                        },
                    }
                },
selectDay() {
    this.date().day.selected = 20;
    console.log(this.date().day.selected) //logs current day (12) instead of 20
}
```

Secondly I defined properties for each (daySelected, dayCurrent for example) but it tells me that today() is not a method

```javascript
today() { return new Date() },
dayCurrent: this.today().getDate(),
daySelected: this.today().getDate()
```

I'm not sure if there is something I am missing here or something in Project-X needs to change.

**Comment by keyurshah** [comment]
there was a release today that fixed the issue for nested objects #18 . Just wanted to mention in case you were testing on a prior version.

**Comment by shaqaruden** [comment]
I guess I should have actually included the error. When I define them as properties it tells me that “this.today() is not a date object”. Do I maybe need to cast it as a date object?

**Comment by shaqaruden** [comment]
I am using the current v0.4.2. I should actually specify the issue I am having. As I said in my OP the first attempt did not work because it was not mutable. The second attempt has this issue

`Unhandled Promise Rejection: TypeError: this.today is not a function. (In 'this.today()', 'this.today' is undefined)` I am using my prevMonth button method for testing and just filled out something in nextMonth().

Here is my entire JS for this.
```javascript
function datepicker() {
            return {
                showPicker: false,
                open() { 
                    this.showPicker = true
                },
                close() { this.showPicker = false },
                isOpen() { return this.showPicker === true },
                formattedMonthYear() { return this.months[0] + ' ' + '2019' },
                today() { return new Date() },
                selectedDay: this.today().getDate(),
                months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October' , 'November', 'December'],
                prevMonth() {
                    console.log('Selected', this.selectedDay)
                    console.log('Current', this.currentDay)
                },
                nextMonth() {
                    console.log('something')
                }
            }
        }
```

**Comment by calebporzio** [comment]
Yeah, the problem is just a JavaScript problem: you can't access the "this" context outside of a function in an object literal.

`selectedDay` needs to be a function to access `this`

You could just make `selectedDay` a function right?

**Comment by shaqaruden** [comment]
@calebporzio i need to be able to mutate it.
