### ISSUE TITLE
maybe lack some styles for quick start in Readme.md#Use

### ISSUE THREAD

**Issue by alienzhou** [calebporzio/project-x#3]
Great project!

Probably the `Readme.md#Use` section needs a `.hidden` style to run, which I found in the `index.html` file.

```html
<style>
  .hidden { display: none; }
</style>
```

Besides the `index.html` won't work automaticly.

**Comment by calebporzio** [comment]
Good call, I added a note for `.hidden`. AND I updated `index.html` to use the CDN link so people can just pull it down.

Thanks!
