### ISSUE TITLE
Add .prevent modifier to click-handler

### ISSUE THREAD

**Issue by lalov** [calebporzio/project-x#4]
Very nice framework! :-) Would be very nice to have "prevent" modifier on a click handler, that way it can be used on anchor-elements. 

Example: 
`
<a class="nav-link" href="#" x-bind:class="{ 'active': tab === 'view' }" x-on:click.prevent="tab = 'view'">View</a>
`

The modifiers you have in Livewire could serve as an example: 
- **stop** 	Equivalent of event.stopPropagation()
- **prevent** 	Equivalent of event.preventDefault()

**Comment by calebporzio** [comment]
Done
